theme: jekyll-theme-minimal
title: Data Sceince Portifolio Projects
Desciption: This page contains my data science projects that focus on NLP, computer vision, Statistical and Machine Learning models.
